resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'

variables:
- name: projectName
  value: 'templ-test47'

- group: ados-group-names-templ-test01
- group: ados-acls-templ-test01
- group: ados-git-params-templ-test01
- group: ados-secrets

parameters:
- name: createArtifactFeed
  displayName: 'Create Artifact Feed?'
  type: boolean
  default: true

jobs:
- job: create_project
  displayName: 'Create project'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7.x'
    inputs:
      versionSpec: 3.7.x

  - bash: |
      pip install --disable-pip-version-check --ignore-installed --quiet --user --requirement requirements.txt
    displayName: 'Install requirements'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/create_project.py
      arguments: '--organization https://dev.azure.com/kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Create $(projectName) project'

  - bash: sleep 10
    displayName: 'Wait for Project APIs to become available..'

  - task: PythonScript@0
    inputs:
      scriptPath: ./cloud/export_project_info.py
      arguments: '--organization kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Export project-related info'

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/create_tmp_release_pipeline.py
      arguments: '--organization https://vsrm.dev.azure.com/kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Create tmp Release pipeline'

  - template: ./templates/delete-groups.yml
  - template: ./templates/create-groups.yml

  - bash: |
      sleep 10
    displayName: 'Wait for Groups objects to become available..'

  - template: ./cloud/templates/export-groups-info.yml
  - template: ./templates/set-project-permissions.yml
  - template: ./templates/set-analytics-permissions.yml
  - template: ./templates/set-library-permissions.yml
  - template: ./templates/set-git.yml
  - template: ./templates/set-build-permissions.yml
  - template: ./templates/set-release-permissions.yml

  - task: PythonScript@0
    inputs:
      scriptPath: ./common/delete_tmp_release_pipeline.py
      arguments: '--organization https://vsrm.dev.azure.com/kagarlickij --projectName $(projectName) --pat $(cloud_pat)'
    displayName: 'Delete tmp Release pipeline'

  - ${{ if eq(parameters.createArtifactFeed, true) }}:
    - template: ./templates/create-feed.yml
